dist: trusty
sudo: false
language: python
matrix:
  include:
    - python: '2.7'
      env: TOXENV=py27 VAULT_VERSION=0.8.3
    - python: '2.7'
      env: TOXENV=py27 VAULT_VERSION=0.11.1
  # - python: '2.7'
  #   env: TOXENV=py27-flake8 VAULT_BRANCH=release
  # - python: '3.6'
  #   env: TOXENV=py36 VAULT_BRANCH=release VAULT_VERSION=0.8.3
  # - python: '3.6'
  #   env: TOXENV=py36 VAULT_BRANCH=release
  # - python: '3.6'
  #   env: TOXENV=py36-flake8 VAULT_BRANCH=release
  # - python: '3.6'
  #   env: TOXENV=py36 VAULT_BRANCH=head
  # allow_failures:
  # - python: '3.6'
  #   env: TOXENV=py36 VAULT_BRANCH=head
install:
  - scripts/install-vault.sh ${VAULT_VERSION}
  - pip install tox
script:
  - export PATH=$HOME/bin:$PATH
  - make test
