dist: xenial
language: python
python:
  - '3.7'
  - '2.7'
env:
  - HVAC_VAULT_VERSION=1.1.3 HVAC_VAULT_LICENSE=enterprise
  - HVAC_VAULT_VERSION=1.0.3 HVAC_VAULT_LICENSE=enterprise
  - HVAC_VAULT_VERSION=0.11.0 HVAC_VAULT_LICENSE=enterprise  # This ver kept explicitly; it has subsequently reverted backwards-incompatible changes.
  - HVAC_VAULT_VERSION=HEAD HVAC_VAULT_LICENSE=OSS
  - TOXENV=flake8
matrix:
  include:
    - name: 'Vault OSS - Latest hvac-tested Release on Python 3.7'
      python: '3.7'
      env: HVAC_VAULT_VERSION=1.1.3 HVAC_VAULT_LICENSE=OSS
    - name: 'Test Documentation Build - Sphinx: "make html"'
      env: TOXENV=docs
  allow_failures:
    # Ignore failed tests run against Vault builds using the HEAD ref at: https://github.com/hashicorp/vault.
    - env: HVAC_VAULT_VERSION=HEAD HVAC_VAULT_LICENSE=OSS
  # Don't wait on the "allow_failures" build jobs before reporting on the overall success/failure of the current build.
  fast_finish: true
install:
  - tests/scripts/install-consul.sh
  - tests/scripts/install-vault.sh ${HVAC_VAULT_VERSION} ${HVAC_VAULT_LICENSE}
  - pip install tox-travis
script:
  - make test
notifications:
  webhooks:
    secure: "IuHvo7I77oZKo++O9QSq1TOtYOvZnqSTg7uO1lr7/+6fMsFLZE4YQVVqa3qyJwn5Q2DafAIdzVj5OyWT9FK8hDTAhqkDL4iVnh+Bk+ph1WBYA0OzFv32K0M46byUwTMmeq51DIuTozhJ/v58pYk6d95MJT9J5/cXCeGmr2vAUqo="
jobs:
  include:
    - stage: PyPi Release
      install: skip
      script: skip
      before_deploy:
        - make package
      deploy:
        provider: pypi
        user: hvac-bot
        password:
          secure: vUZrUEYhQk+MhPyUAkUWAimnBzc8BvMkyYgZjvMSuIAM5hNNazp7gT/6gz6lO+R73l3NTGjBqL1zmaMl1JzWi/QhMGjaaxbuMMVl4xsuXVOSIU3gsQ2PlvVMzdFjbKSldvUbo6Q4OTleutBYfqDZThgD+415EJkQ0i5af3NeKzOpOhw+Ki5UdASK2c9czarpnkKQcDGwETyvY05aqwiSbWwW4xrsbAVm90WcSJEL8+J78gAF9ZY+DVqn3e2quN1O5UilS+XP1SvwiPhJU8YDpZpLS3i9iX4lkxLgUIYuPLxL+E3KgAPGsDTgW/sgqiXoRFYG8GilaUyhAYD1n2GrVklH7/nk5LPZKRErTPanVLjpWPv+ReEXnfa5mk50mNDde9HvTLdxcnQLN+JVYduN4kSnqw1Oiq33xMJzeksu9My7EouCY7ok/L5123vgYESIGJ7plLtPjKI3I3Y3NVjVPLV3WOXe29VUh0pZMstnzKzu4XUbU12yA/gHUp8LaoFLHGiDEJG3mbSEFu3rPstyUMsnwGcZhBKW17bc0kq4aYMxzjSGw7M6MeB/+ZfUmLj2cCNEtzNF+sK3kZKhrGuYDtV/SBkdIHRvdzk0T3vkyZGzb34sIyFdADkHCBb3JTyD2JH9LauwALG6xfR4KMOmA5z2lAEBjVdgyTXMv8J5fDY=
        distributions: "sdist bdist_wheel"
        server: https://test.pypi.org/legacy/
        skip_cleanup: true
        on:
          tags: true
